### ISSUE TITLE
java版报错

### ISSUE THREAD

**Issue by 111304037** [hack0z/byOpen#12]
java版报错，load.invoke时直接抛出异常了
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at dyopen.lib.SystemLoader.load(SystemLoader.java:40)
        at java.lang.reflect.Method.invoke(Native Method)

**Comment by 111304037** [comment]
java.lang.UnsatisfiedLinkError: 
        at java.lang.Runtime.load0(Runtime.java:944)
        at java.lang.System.load(System.java:1639)
        at java.lang.reflect.Method.invoke(Native Method)
        at dyopen.lib.SystemLoader.load(SystemLoader.java:43)
