### ISSUE TITLE
byOpen可以加载/system/lib之外的例如SD卡当中的so吗

### ISSUE THREAD

**Issue by spianmo** [hack0z/byOpen#2]

**Comment by spianmo** [comment]
实测LOG如下
`java.lang.UnsatisfiedLinkError: Directory separator should not appear in library name: /storage/emulated/0/libcurl.so
        at java.lang.Runtime.loadLibrary0(Runtime.java:1052)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at java.lang.Runtime.nativeLoad(Native Method)
        at java.lang.Runtime.nativeLoad(Runtime.java:1115)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1069)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)`

**Comment by spianmo** [comment]
好像是/目录分隔符导致的UnsatisfiedLinkError，但是/system/lib/libxx.so也包含目录分隔符，为什么却可以加载成功呢

**Comment by liuyou** [comment]
sd卡能被加载的前提是 文件系统得是ext，否则 fat文件系统的文件 都不能mmap，谈何加载成功

**Comment by spianmo** [comment]
> sd卡能被加载的前提是 文件系统得是ext，否则 fat文件系统的文件 都不能mmap，谈何加载成功

感谢解答
